name: compile sonar-netcd4 into PDF

on: 
  push:
    paths:
      - 'SONAR-netCDF4'

jobs:
  runs-on: ubuntu-latest
  steps:
    # comment
    - uses: actions/checkout@v2
    - uses mgred/scidoctor-action@master
      with:
        args: asciidoctor crr341.adoc
